name: GreenPots
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  wifi_iot: ^0.3.4

  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^3.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:

  uses-material-design: true


  assets:
    - assets/icon/app_icon.png
